### ISSUE TITLE
Can we use this code for feature extraction?

### ISSUE THREAD

**Issue by Rasipuram** [InnovArul/first-impressions#2]
Hi Arul,
Can we use the pre-trained models in your repository for feature extraction?
I installed OpenFace and pyAudioAnalysis libraries. 

Can you please share the details to use this code for feature extraction alone without any training?

**Comment by InnovArul** [comment]
We haven't used our models for feature extraction. Ideally, it should be possible to do. You can write a script similar to [validate.lua](https://github.com/InnovArul/first-impressions/blob/master/src/5_validate.lua). You can extract the features from fully connected layers after [`forward`ing](https://github.com/InnovArul/first-impressions/blob/master/src/5_validate.lua#L70) the data through the model.

You can access the layer outputs in the normal way as any other torch `nngraph` model.
```
model = torch.load('<model.net>')
model:forward(data)
features = model.modules[FC_LAYER_INDEX].output:clone()
```

**Comment by Rasipuram** [comment]
Thank you very much. I will surely try along these lines.

**Comment by Rasipuram** [comment]
Hi Arul,
Your answer is well appreciated. 

But I feel difficult to run these codes for my data. I am not sure where to start with. 
How to place my mp4 data in proper directories, as the data given in the link is not downloadable?

It would be very helpful if there are commands for feature extraction alone (for our data). 

I request you to please share your thoughts.

**Comment by InnovArul** [comment]
Please go through the files `data/preprocessing_videofeats.py`, `data/preprocessing_audiofeats.py` to know the commands for feature extraction.

The extracted features shall be placed in the below folders (automatically done by these scripts). 
```
"data/trainaudiofeat" - training audio features 
"data/trainframes" - training video features 
"data/validationaudiofeat" - validation audio features 
"data/validationframes" - validation video features
```

Also, the original data from the competition is downloadable from organizer's [website](http://chalearnlap.cvc.uab.es/dataset/20/data/32/files/).

**Comment by InnovArul** [comment]
Closing the issue assuming that the issue was resolved, please reopen/create a new issue if there is any help/clarification needed. Thanks!
