### ISSUE TITLE
How to import and run the test videos on LSTMModel#440.net

### ISSUE THREAD

**Issue by sridharswain** [InnovArul/first-impressions#3]
Hello,

I am able to import the file
by
require "nn"
require "cunn"
require "rnn"
net = torch.load("LSTMModel#440.net")

but I don't understand how to use it.

it throws an error saying

torch.load("LSTMModel#440.net")
/home/conankapoor/torch/install/bin/luajit: ...or/torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:287: attempt to call field '__tostring__' (a nil value)
stack traceback:
	...or/torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:287: in function <...or/torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:283>
	[C]: in function 'tostring'
	...onankapoor/torch/install/share/lua/5.1/nn/Sequential.lua:118: in function <...onankapoor/torch/install/share/lua/5.1/nn/Sequential.lua:107>
	[C]: in function 'tostring'
	...e/conankapoor/torch/install/share/lua/5.1/trepl/init.lua:262: in function 'rawprint'
	...e/conankapoor/torch/install/share/lua/5.1/trepl/init.lua:302: in function 'print'
	...e/conankapoor/torch/install/share/lua/5.1/trepl/init.lua:663: in function 'repl'
	...poor/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x00405d50

**Comment by InnovArul** [comment]
Probably its an utterly late reply! I am sorry for that!

In our implementation of the model, we used an LSTM implementation from [here](https://github.com/garythung/torch-lrcn.git). 
It is present in  **./src** folder. [https://github.com/InnovArul/first-impressions/blob/master/src/LSTM.lua](https://github.com/InnovArul/first-impressions/blob/master/src/LSTM.lua).

To avoid the error, 

1. please place this file (LSTM.lua) in your directory.
2. change `require 'rnn'` to `require 'LSTM'`

Hope it helps!

**Comment by InnovArul** [comment]
I assume the issue is resolved. Please feel free to reopen.
