### ISSUE TITLE
visualization software 

### ISSUE THREAD

**Issue by amirim** [InnovArul/first-impressions#5]
Hi,

I was wondering in which software tool have you used in order to generate the network's visualization as seen in your paper: "Bi-modal First Impressions Recognition using Temporally Ordered Deep Audio and Stochastic Visual Features".
<img width="401" alt="screen shot 2018-03-18 at 5 04 25 pm" src="https://user-images.githubusercontent.com/32954177/38465940-604fc464-3b2a-11e8-867b-a9f070511da2.png">

**Comment by InnovArul** [comment]
We created the diagrams using Ubuntu package LibreOffice Writer (similar to Microsoft word).

**Comment by amirim** [comment]
the diagram looks very attractive, but with LibreOffice it seams like a lot of manual work, are you familiar with another methods that do that automatically while the input is the network's code (written in any library) and the output is this kind of diagram?

**Comment by InnovArul** [comment]
right, it's manual work. Once you get to practice, you will find it easier I guess, just like writing a paper. I haven't come across such methods to generate diagrams automatically from code. If you have come across any such things, please do share :)
